// Generated by gencpp from file grasp_demo/EyetoHandRequest.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_EYETOHANDREQUEST_H
#define GRASP_DEMO_MESSAGE_EYETOHANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_demo
{
template <class ContainerAllocator>
struct EyetoHandRequest_
{
  typedef EyetoHandRequest_<ContainerAllocator> Type;

  EyetoHandRequest_()
    : marker_x(0.0)
    , marker_y(0.0)
    , marker_z(0.0)  {
    }
  EyetoHandRequest_(const ContainerAllocator& _alloc)
    : marker_x(0.0)
    , marker_y(0.0)
    , marker_z(0.0)  {
  (void)_alloc;
    }



   typedef double _marker_x_type;
  _marker_x_type marker_x;

   typedef double _marker_y_type;
  _marker_y_type marker_y;

   typedef double _marker_z_type;
  _marker_z_type marker_z;





  typedef boost::shared_ptr< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EyetoHandRequest_

typedef ::grasp_demo::EyetoHandRequest_<std::allocator<void> > EyetoHandRequest;

typedef boost::shared_ptr< ::grasp_demo::EyetoHandRequest > EyetoHandRequestPtr;
typedef boost::shared_ptr< ::grasp_demo::EyetoHandRequest const> EyetoHandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_demo::EyetoHandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_demo::EyetoHandRequest_<ContainerAllocator1> & lhs, const ::grasp_demo::EyetoHandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.marker_x == rhs.marker_x &&
    lhs.marker_y == rhs.marker_y &&
    lhs.marker_z == rhs.marker_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_demo::EyetoHandRequest_<ContainerAllocator1> & lhs, const ::grasp_demo::EyetoHandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "871dc000c2d2d2ebd9de156d820ffa1c";
  }

  static const char* value(const ::grasp_demo::EyetoHandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x871dc000c2d2d2ebULL;
  static const uint64_t static_value2 = 0xd9de156d820ffa1cULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_demo/EyetoHandRequest";
  }

  static const char* value(const ::grasp_demo::EyetoHandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 marker_x\n"
"float64 marker_y\n"
"float64 marker_z\n"
;
  }

  static const char* value(const ::grasp_demo::EyetoHandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.marker_x);
      stream.next(m.marker_y);
      stream.next(m.marker_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EyetoHandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_demo::EyetoHandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_demo::EyetoHandRequest_<ContainerAllocator>& v)
  {
    s << indent << "marker_x: ";
    Printer<double>::stream(s, indent + "  ", v.marker_x);
    s << indent << "marker_y: ";
    Printer<double>::stream(s, indent + "  ", v.marker_y);
    s << indent << "marker_z: ";
    Printer<double>::stream(s, indent + "  ", v.marker_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_EYETOHANDREQUEST_H
