// Generated by gencpp from file grasp_demo/EyetoHandResponse.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_EYETOHANDRESPONSE_H
#define GRASP_DEMO_MESSAGE_EYETOHANDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grasp_demo
{
template <class ContainerAllocator>
struct EyetoHandResponse_
{
  typedef EyetoHandResponse_<ContainerAllocator> Type;

  EyetoHandResponse_()
    : obj_x(0.0)
    , obj_y(0.0)
    , obj_z(0.0)  {
    }
  EyetoHandResponse_(const ContainerAllocator& _alloc)
    : obj_x(0.0)
    , obj_y(0.0)
    , obj_z(0.0)  {
  (void)_alloc;
    }



   typedef double _obj_x_type;
  _obj_x_type obj_x;

   typedef double _obj_y_type;
  _obj_y_type obj_y;

   typedef double _obj_z_type;
  _obj_z_type obj_z;





  typedef boost::shared_ptr< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EyetoHandResponse_

typedef ::grasp_demo::EyetoHandResponse_<std::allocator<void> > EyetoHandResponse;

typedef boost::shared_ptr< ::grasp_demo::EyetoHandResponse > EyetoHandResponsePtr;
typedef boost::shared_ptr< ::grasp_demo::EyetoHandResponse const> EyetoHandResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grasp_demo::EyetoHandResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grasp_demo::EyetoHandResponse_<ContainerAllocator1> & lhs, const ::grasp_demo::EyetoHandResponse_<ContainerAllocator2> & rhs)
{
  return lhs.obj_x == rhs.obj_x &&
    lhs.obj_y == rhs.obj_y &&
    lhs.obj_z == rhs.obj_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grasp_demo::EyetoHandResponse_<ContainerAllocator1> & lhs, const ::grasp_demo::EyetoHandResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grasp_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ee63385c214e38ca46f0e8b25b9b4dc";
  }

  static const char* value(const ::grasp_demo::EyetoHandResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ee63385c214e38cULL;
  static const uint64_t static_value2 = 0xa46f0e8b25b9b4dcULL;
};

template<class ContainerAllocator>
struct DataType< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grasp_demo/EyetoHandResponse";
  }

  static const char* value(const ::grasp_demo::EyetoHandResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 obj_x\n"
"float64 obj_y\n"
"float64 obj_z\n"
"\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::grasp_demo::EyetoHandResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_x);
      stream.next(m.obj_y);
      stream.next(m.obj_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EyetoHandResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grasp_demo::EyetoHandResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grasp_demo::EyetoHandResponse_<ContainerAllocator>& v)
  {
    s << indent << "obj_x: ";
    Printer<double>::stream(s, indent + "  ", v.obj_x);
    s << indent << "obj_y: ";
    Printer<double>::stream(s, indent + "  ", v.obj_y);
    s << indent << "obj_z: ";
    Printer<double>::stream(s, indent + "  ", v.obj_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_EYETOHANDRESPONSE_H
