// Generated by gencpp from file grasp_demo/EyetoHand.msg
// DO NOT EDIT!


#ifndef GRASP_DEMO_MESSAGE_EYETOHAND_H
#define GRASP_DEMO_MESSAGE_EYETOHAND_H

#include <ros/service_traits.h>


#include <grasp_demo/EyetoHandRequest.h>
#include <grasp_demo/EyetoHandResponse.h>


namespace grasp_demo
{

struct EyetoHand
{

typedef EyetoHandRequest Request;
typedef EyetoHandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EyetoHand
} // namespace grasp_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grasp_demo::EyetoHand > {
  static const char* value()
  {
    return "9743f28c3a9d1b192b8ad805848bdee3";
  }

  static const char* value(const ::grasp_demo::EyetoHand&) { return value(); }
};

template<>
struct DataType< ::grasp_demo::EyetoHand > {
  static const char* value()
  {
    return "grasp_demo/EyetoHand";
  }

  static const char* value(const ::grasp_demo::EyetoHand&) { return value(); }
};


// service_traits::MD5Sum< ::grasp_demo::EyetoHandRequest> should match
// service_traits::MD5Sum< ::grasp_demo::EyetoHand >
template<>
struct MD5Sum< ::grasp_demo::EyetoHandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_demo::EyetoHand >::value();
  }
  static const char* value(const ::grasp_demo::EyetoHandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_demo::EyetoHandRequest> should match
// service_traits::DataType< ::grasp_demo::EyetoHand >
template<>
struct DataType< ::grasp_demo::EyetoHandRequest>
{
  static const char* value()
  {
    return DataType< ::grasp_demo::EyetoHand >::value();
  }
  static const char* value(const ::grasp_demo::EyetoHandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grasp_demo::EyetoHandResponse> should match
// service_traits::MD5Sum< ::grasp_demo::EyetoHand >
template<>
struct MD5Sum< ::grasp_demo::EyetoHandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grasp_demo::EyetoHand >::value();
  }
  static const char* value(const ::grasp_demo::EyetoHandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grasp_demo::EyetoHandResponse> should match
// service_traits::DataType< ::grasp_demo::EyetoHand >
template<>
struct DataType< ::grasp_demo::EyetoHandResponse>
{
  static const char* value()
  {
    return DataType< ::grasp_demo::EyetoHand >::value();
  }
  static const char* value(const ::grasp_demo::EyetoHandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASP_DEMO_MESSAGE_EYETOHAND_H
